---
- name: Install zabbix-agent2
  hosts: all
  become: yes
  tasks:
    - name: Add Zabbix repository
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu focal main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install zabbix-agent2
      apt:
        name: zabbix-agent2
        state: present
      when: ansible_os_family == "Debian"

    - name: Configure zabbix-agent2
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server }}"
        state: present

    - name: Restart zabbix-agent2
      service:
        name: zabbix-agent2
        state: restarted
